openapi: 3.0.1
info:
  title: API for Index Of Industrial Production (IIP)

  version: 1.0.11
servers:
- url: https://api.mospi.gov.in/
tags:
- name: IIP Annual Index and GrowthRate.
  description: Index and GrowthRate For Annual Data.
- name: IIP Monthly Index and GrowthRate
  description: 'Index and GrowthRate For Monthly Data.'
paths:

  /api/iip/getIIPAnnual:
    get:
      tags:
      - IIP Annual Index and GrowthRate.
      operationId: IIPAnnualIndexAndGrowthRate
      parameters:
      - name: base_year
        required: true
        in: query
        schema:
          default: "2011-12"
          enum:
          - "2011-12"
          - "2004-05"
          - "1993-94"
      - name: financial_year
        in: query
        description: Enter the Financial Year (format YYYY-YY.Comma separated for multiple values)
        schema:
          type: string
      - name: category_code
        in: query
        description: Enter the Category code (from 01 to 11.Comma separated for multiple values)
        schema:
          type: string
      - name: subcategory_code
        in: query
        description: Enter the Subcategory code (Kindly refer to the Metadata sheet available by clicking the "View Metadata" button)
        schema:
          type: string
      - name: limit
        in: query
        description: Number of records per page (default 10)
        schema:
          type: integer
      - name: page
        in: query
        description: Enter the page no. (from 1 to n.)
        schema:
          type: string
      - name: type
        required: true
        in: query
        schema:
          default: All
          enum:
          - All
          - Use-based category
          - Sectoral
          - General
      - name: Format
        required: true
        in: query
        description: Select the Output format
        schema:
          type: string
          default: JSON
          enum:
          - JSON
          - CSV
      responses:
        "200":
          description: A JSON array of user information
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
            text/csv:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
      
        "409":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Requested item wasn't found!
      security:
      - bearerAuth: []
  /api/iip/getIIPMonthly:
    get:
      tags:
      - IIP Monthly Index and GrowthRate
      operationId: IIPMonthlyIndexAndGrowthRate
      parameters:
      - name: base_year
        required: true
        in: query
        schema:
          default: "2011-12"
          enum:
          - "2011-12"
          - "2004-05"
          - "1993-94"
      - name: year
        in: query
        description:  Enter the Year (format YYYY.Comma separated for multiple values)
        schema:
          type: string
      - name: month_code
        in: query
        description: Enter the Month code (from 1-12.Comma separated for multiple values)
        schema:
          type: string
      - name: category_code
        in: query
        description: Enter the Category code (from 01 to 11.Comma separated for multiple values)
        schema:
          type: string
      - name: subcategory_code
        in: query
        description: Enter the Subcategory code (Kindly refer to the Metadata sheet available by clicking the "View Metadata" button)
        schema:
          type: string
      - name: limit
        in: query
        description: Number of records per page (default 10)
        schema:
          type: integer
      - name: page
        in: query
        description: Enter the page no. (from 1 to n.)
        schema:
          type: string
      - name: type
        required: true
        in: query
        schema:
          default: All
          enum:
          - All
          - Use-based category
          - Sectoral
          - General
      - name: Format
        required: true
        in: query
        description: Select the Output format
        schema:
          type: string
          default: JSON
          enum:
          - JSON
          - CSV
      responses:
        "200":
          description: A JSON array of user information

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
            text/csv:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
      
        "409":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Requested item wasn't found!
     
      security:
      - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      description: Bearer token to access these api endpoints
      name: Authorization
      in: header
x-original-swagger-version: "2.0"
