openapi: 3.0.1
info:
  title: Energy Statistics
  version: 1.0.11
servers:
- url: https://api.mospi.gov.in/
tags:
- name: Energy Statistics.
  description: Year-Wise Energy Statistics.
paths:

  /api/energy/getEnergyRecords:
    get:
      tags:
      - Energy Statistics.
      operationId: ENERGYIndicatorValues.
      parameters:
      - name: indicator_code
        required: true
        in: query
        schema:
          default: "Energy Balance ( in KToE )"
          enum:
          - "Energy Balance ( in KToE )"
          - "Energy Balance ( in PetaJoules )"
      - name: use_of_energy_balance_code
        required: true
        in: query
        schema:
          default: "Supply"
          enum:
          - "Supply"
          - "Consumption"
      - name: year
        in: query
        description: Enter the Year (format YYYY-YY/YYYY. Comma separated for multiple values)
        schema:
          type: string
      - name: energy_commodities_code
        in: query
        description: Enter the Energy Commodities code (from 1 to 10. Comma separated for multiple values)
        schema:
          type: string
      - name: energy_sub_commodities_code
        in: query
        description: Enter the Energy Sub_commodities code (from 1 to 12. Comma separated for multiple values)
        schema:
          type: string
      - name: end_use_sector_code
        in: query
        description: Enter the End Use Sector code (from 1 to 10. Comma separated for multiple values)
        schema:
          type: string
      - name: end_use_sub_sector_code
        in: query
        description: Enter the End Use Sub_sector code (from 1 to 22. Comma separated for multiple values)
        schema:
          type: string
      - name: limit
        in: query
        description: Number of records per page (default 10)
        schema:
          type: integer
      - name: page
        in: query
        description: Enter the page no. (from 1 to n.)
        schema:
          type: string
      - name: Format
        required: true
        in: query
        description: Select the Output format
        schema:
          type: string
          default: JSON
          enum:
          - JSON
          - CSV
      responses:
        "200":
          description: A JSON array of user information
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
            text/csv:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
      
        "409":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Requested item wasn't found!
      security:
      - bearerAuth: []
 
components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      description: Bearer token to access these api endpoints
      name: Authorization
      in: header
x-original-swagger-version: "2.0"
