openapi: 3.0.1
info:
  title: Annual Survey of Unincorporated Sector Enterprises (ASUSE)

  version: 1.0.11
servers:
- url: https://api.mospi.gov.in/
tags:
- name: Annual Survey of Unincorporated Sector Enterprises.
  description: Year-Wise Annual Survey of Unincorporated Sector Enterprises (ASUSE).
paths:

  /api/asuse/getAsuseRecords:
    get:
      tags:
      - Annual Survey of Unincorporated Sector Enterprises.
      operationId: ASUSEIndicatorValues.
      parameters:
      - name: indicator_code
        required: true
        in: query
        schema:
          type: integer
      - name: year
        in: query
        description: Enter the Year (format YYYY-YY. Comma separated for multiple values)
        schema:
          type: string
      - name: state_ut_code
        in: query
        description: Enter the State/UT code (from 1 to 37. Comma separated for multiple values)
        schema:
          type: integer
      - name: sub_indicator_code
        in: query
        description: Enter the Sub Indicator code (from 1 to 19. Comma separated for multiple values)
        schema:
          type: integer
      - name: activity_category_code
        in: query
        description: Enter the Activity Category code (from 1 to 50. Comma separated for multiple values)
        schema:
          type: integer
      - name: sector_code
        in: query
        description: Enter the Sector code (from 1 to 3. Comma separated for multiple values)
        schema:
          type: integer
      - name: gender_code
        in: query
        description: Enter the Gender code (from 1 to 4. Comma separated for multiple values)
        schema:
          type: integer
      - name: ownership_type_code
        in: query
        description: Enter the Ownership Type code (from 1 to 8. Comma separated for multiple values)
        schema:
          type: integer
      - name: establishment_type_code
        in: query
        description: Enter the Establishment Type code (from 1 to 3. Comma separated for multiple values)
        schema:
          type: integer
      - name: general_education_level_code
        in: query
        description: Enter the General Education Level code (from 1 to 7. Comma separated for multiple values)
        schema:
          type: integer
      - name: social_group_of_owner_major_partner_code
        in: query
        description: Enter the Social Group of Owner/Major Partner code (from 1 to 6. Comma separated for multiple values)
        schema:
          type: integer
      - name: broad_activity_category_code
        in: query
        description: Enter the Broad Activity Category code (from 1 to 4. Comma separated for multiple values)
        schema:
          type: integer
      - name: other_economic_activitycount_code
        in: query
        description: Enter the Other Economic Activitycount code (from 1 to 6. Comma separated for multiple values)
        schema:
          type: integer
      - name: account_holder_code
        in: query
        description: Enter the Account Holder code (from 1 to 3. Comma separated for multiple values)
        schema:
          type: integer
      - name: location_of_establishments_code
        in: query
        description: Enter the Location of Establishments code (from 1 to 7. Comma separated for multiple values)
        schema:
          type: integer
      - name: nature_of_operation_code
        in: query
        description: Enter the Nature of Operation code (from 1 to 4. Comma separated for multiple values)
        schema:
          type: integer
      - name: no_of_months_operated_code
        in: query
        description: Enter the No. of Months Operated code (from 1 to 6. Comma separated for multiple values)
        schema:
          type: integer
      - name: no_of_working_hours_code
        in: query
        description: Enter the No. of Working Hours code (from 1 to 5. Comma separated for multiple values)
        schema:
          type: integer
      - name: audit_status_code
        in: query
        description: Enter the Audit Status code (from 1 to 3. Comma separated for multiple values)
        schema:
          type: integer
      - name: npi_status_code
        in: query
        description: Enter the NPI Status code (from 1 to 4. Comma separated for multiple values)
        schema:
          type: integer
      - name: acts_agency_of_registration_code
        in: query
        description: Enter the Acts/Agency of Registration code (from 1 to 10. Comma separated for multiple values)
        schema:
          type: integer
      - name: services_contract_code
        in: query
        description: Enter the Services Contract code (from 1 to 5. Comma separated for multiple values)
        schema:
          type: integer
      - name: nature_of_employment_code
        in: query
        description: Enter the Nature of Employment code (from 1 to 3. Comma separated for multiple values)
        schema:
          type: integer
      - name: type_of_worker_code
        in: query
        description: Enter the Type of Worker code (from 1 to 6. Comma separated for multiple values)
        schema:
          type: integer
      - name: hired_worker_code
        in: query
        description: Enter the Hired Worker code (from 1 to 3. Comma separated for multiple values)
        schema:
          type: integer
      - name: fixed_assets_code
        in: query
        description: Enter the Fixed Assets code (from 1 to 3. Comma separated for multiple values)
        schema:
          type: integer
      - name: usage_of_internet_code
        in: query
        description: Enter the Usage of Internet code (from 1 to 13. Comma separated for multiple values)
        schema:
          type: integer
      - name: worker_characteristics_code
        in: query
        description: Enter the Worker Characteristics code (from 1 to 7. Comma separated for multiple values)
        schema:
          type: integer
      - name: worker_number_code
        in: query
        description: Enter the Worker Number code (from 1 to 21. Comma separated for multiple values)
        schema:
          type: integer
      - name: frequency_code
        in: query
        description: Annually,monthly,quaterly
        schema:
          type: integer  
      - name: page
        in: query
        description: Enter the page no. (from 1 to n.)
        schema:
          type: integer

      - name: Format 
        required: true
        in: query
        description: Select the Output format
        schema:
          type: string
          default: JSON
          enum:
          - JSON
          - CSV
      responses:
        "200":
          description: A JSON array of user information
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
            text/csv:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
      
        "409":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Requested item wasn't found!
      security:
      - bearerAuth: []
 
components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      description: Bearer token to access these api endpoints
      name: Authorization
      in: header
x-original-swagger-version: "2.0"
