openapi: 3.0.1
info:
  title: Annual Survey of Industries (ASI)

  version: 1.0.11
servers:
- url: https://api.mospi.gov.in/
tags:
- name: Annual Survey of Industries.
  description: All-India and State-wise Annual Survey of Industries (ASI).
paths:

  /api/asi/getASIData:
    get:
      tags:
      - Annual Survey of Industries.
      operationId: ASIIndicatorValues.
      parameters:
      - name: classification_year
        required: true
        in: query
        schema:
          default: "2008"
          enum:
          - "2008"
          - "2004"
          - "1998"
          - "1987"
      - name: sector_code
        required: true
        in: query
        schema:
          default: "Combined"
          enum:
          - "Rural"
          - "Urban"
          - "Combined"
      - name: year
        in: query
        description: Enter the Year (format YYYY-YY.Comma separated for multiple values)
        schema:
          type: string
      - name: indicator_code
        in: query
        description: Enter the Indicator code (from 1 to 57. Comma separated for multiple values)
        schema:
          type: string
      - name: state_code
        in: query
        description: Enter the State code (from 1 to 38. 88 for Dadra & N Haveli & Daman & Diu and 99 for All India .Comma separated for multiple values)
        schema:
          type: string
      - name: nic_code
        in: query
        description: Enter the NIC code (Please refer the metadata sheet. Comma separated for multiple values)
        schema:
          type: string
      - name: limit
        in: query
        description: Number of records per page (default 10)
        schema:
          type: integer
      - name: page
        in: query
        description: Enter the page no. (from 1 to n.)
        schema:
          type: string
      - name: nic_type
        required: true
        in: query
        schema:
          default: All
          enum:
          - All
          - 2-digit
          - 3-digit
          - 4-digit
      - name: Format 
        required: true
        in: query
        description: Select the Output format
        schema:
          type: string
          default: JSON
          enum:
          - JSON
          - CSV
      responses:
        "200":
          description: A JSON array of user information
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
            text/csv:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
      
        "409":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Requested item wasn't found!
      security:
      - bearerAuth: []
 
components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      description: Bearer token to access these api endpoints
      name: Authorization
      in: header
x-original-swagger-version: "2.0"
