openapi: 3.0.1
info:
  title: Periodic Labour Force Survey (PLFS)

  version: 1.0.11
servers:
  - url: https://api.mospi.gov.in/
tags:
  - name: Periodic Labour Force Survey.
    description: Indicator-wise Periodic Labour Force Survey (PLFS).
paths:

  /api/plfs/getData:
    get:
      tags:
        - Periodic Labour Force Survey.
      operationId: PLFSIndicatorValues.
      parameters:

        - name: indicator_code
          required: true
          in: query
          description: Enter the Indicator Code (1 - 8)
          schema:
            type: integer
        - name: frequency_code
          required: true
          in: query
          description: Enter the Frequency Code (1 - Annually, 2 - Quarterly, 3 - Monthly)
          schema:
            type: string
        - name: year
          in: query
          description: Enter the Financial Year (format YYYY-YY. Comma separated for multiple values)
          schema:
            type: string
        - name: month_code
          in: query
          description: Enter the Month code (from 1 to 12. Comma separated for multiple values)
          schema:
            type: string
        - name: state_code
          in: query
          description: Enter the State code (from 1 to 38. Comma separated for multiple values)
          schema:
            type: string
        - name: gender_code
          in: query
          description: Enter the Gender code (from 1 to 3. Comma separated for multiple values)
          schema:
            type: string
        - name: age_code
          in: query
          description: Enter the Age code (from 1 to 4. Comma separated for multiple values)
          schema:
            type: string
        - name: sector_code
          in: query
          description: Enter the Sector code (from 1 to 3. Comma separated for multiple values)
          schema:
            type: string
        - name: weekly_status_code
          in: query
          description: Enter the Weekly Status code (from 1 to 2. Comma separated for multiple values)
          schema:
            type: string
        - name: religion_code
          in: query
          description: Enter the Religion code (from 1 to 5. Comma separated for multiple values)
          schema:
            type: string
        - name: social_category_code
          in: query
          description: Enter the Social category code (from 1 to 5. Comma separated for multiple values)
          schema:
            type: string
        - name: education_code
          in: query
          description: Enter the Education code (from 1 to 10. Comma separated for multiple values)
          schema:
            type: string
        - name: broad_industry_work_code
          in: query
          description: Enter the Broad industry work code (from 1 to 4. Comma separated for multiple values)
          schema:
            type: string
        - name: broad_status_employment_code
          in: query
          description: Enter the Broad status employment code (from 1 to 6. Comma separated for multiple values)
          schema:
            type: string
        - name: employee_contract_code
          in: query
          description: Enter the Employee contract code (from 1 to 5. Comma separated for multiple values)
          schema:
            type: string
        - name: enterprise_size_code
          in: query
          description: Enter the Enterprise size code (from 1 to 6. Comma separated for multiple values)
          schema:
            type: string
        - name: enterprise_type_code
          in: query
          description: Enter the Enterprise type code (from 1 to 9. Comma separated for multiple values)
          schema:
            type: string
        - name: industry_section_code
          in: query
          description: Enter the Industry section code (from 1 to 22. Comma separated for multiple values)
          schema:
            type: string
        - name: nco_division_code
          in: query
          description: Enter the NCO division code (from 1 to 11. Comma separated for multiple values)
          schema:
            type: string
        - name: nic_group_code
          in: query
          description: Enter the NIC group code (from 1 to 14. Comma separated for multiple values)
          schema:
            type: string
        - name: quarter_code
          in: query
          description: Enter the Quarter code (from 1 to 35. Comma separated for multiple values)
          schema:
            type: string
        - name: limit
          in: query
          description: Number of records per page (default 10)
          schema:
            type: integer
        - name: page
          in: query
          description: Enter the page no. (from 1 to n.)
          schema:
            type: string
        - name: Format
          required: true
          in: query
          description: Select the Output format
          schema:
            type: string
            default: JSON
            enum:
              - JSON
              - CSV
      responses:
        "200":
          description: A JSON array of user information
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
            text/csv:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body

        "409":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Requested item wasn't found!
      security:
        - bearerAuth: [ ]

components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      description: Bearer token to access these api endpoints
      name: Authorization
      in: header
x-original-swagger-version: "2.0"
