openapi: 3.0.1
info:
  title: Wholesale Price Index (WPI)

  version: 1.0.11
servers:
- url: https://api.mospi.gov.in/
tags:
- name: Wholesale Price Index.
  description: Year-Wise Wholesale Price Index (WPI).
paths:

  /api/wpi/getWpiRecords:
    get:
      tags:
      - Wholesale Price Index.
      operationId: WPIIndicatorValues.
      parameters:
      - name: year
        in: query
        description: Enter the Year (format YYYY. Comma separated for multiple values)
        schema:
          type: string
      - name: month_code
        in: query
        description: Enter the Month code (from 1 to 12. Comma separated for multiple values)
        schema:
          type: string
      - name: major_group_code
        in: query
        description: Enter the Major group code (Comma separated for multiple values, Refer MetaData Sheet)
        schema:
          type: string
      - name: group_code
        in: query
        description: Enter the Group code (Comma separated for multiple values, Refer MetaData Sheet)
        schema:
          type: string
      - name: sub_group_code
        in: query
        description: Enter the Sub group code (Comma separated for multiple values, Refer MetaData Sheet)
        schema:
          type: string
      - name: sub_sub_group_code
        in: query
        description: Enter the Sub sub group code (Comma separated for multiple values, Refer MetaData Sheet)
        schema:
          type: string
      - name: item_code
        in: query
        description: Enter the Item code (Comma separated for multiple values, Refer MetaData Sheet)
        schema:
          type: string
      - name: limit
        in: query
        description: Number of records per page (default 10)
        schema:
          type: integer
      - name: page
        in: query
        description: Enter the page no. (from 1 to n.)
        schema:
          type: string
      - name: Format
        required: true
        in: query
        description: Select the Output format
        schema:
          type: string
          default: JSON
          enum:
          - JSON
          - CSV
      responses:
        "200":
          description: A JSON array of user information
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
            text/csv:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body

        "409":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Requested item wasn't found!
      security:
      - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      description: Bearer token to access these api endpoints
      name: Authorization
      in: header
x-original-swagger-version: "2.0"
