openapi: 3.0.1
info:
  title: API for Consumer Price Index(CPI AL and RL)
  version: 1.0.11
servers:
- url: https://api.mospi.gov.in/
tags:
- name: Consumer Price Index AL and RL
  description: All-India and State-wise Consumer Price Index AL and RL.
paths:
  /api/cpialrl/getCpialrlRecords:
    get:
      tags:
      - Consumer Price Index AL and RL
      operationId: CPIALRLIndicatorValues.
      parameters:
      - name: indicator_code
        required: true
        in: query
        schema:
          default: "General Index"
          enum:
          - "General Index"
          - "Group Index"
      - name: base_year_code
        in: query
        description: Enter the Year (Comma separated for multiple values)
        schema:
          type: string

      - name: year
        in: query
        description:  Enter the Year (format YYYY-YYYY.Comma separated for multiple values)
        schema:
          type: string
      - name: month_code
        in: query
        description: Enter the Month code (from 1-12.Comma separated for multiple values)
        schema:
          type: string
      - name: state_code
        in: query
        description:  Enter the State code (from 1-38 & 99 for all india comma separated for multiple values)
        schema:
          type: string
      - name: groups_code
        in: query
        description: Enter the Groups code(from 1-6. Comma separated for multiple values)
        schema:
          type: string
      - name: page
        in: query
        description: Enter the page no. (from 1 to n.)
        schema:
          type: string
      - name: Format
        required: true
        in: query
        description: Select the Output format
        schema:
          type: string
          default: JSON
          enum:
          - JSON
          - CSV
      responses:
        "200":
          description: A JSON array of user information
      
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
            text/csv:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
      
        "409":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Requested item wasn't found!
     
      security:
      - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      description: Bearer token to access these api endpoints
      name: Authorization
      in: header
x-original-swagger-version: "2.0"
