openapi: 3.0.1
info:
  title: All India Survey on Higher Education
  version: 1.0.0
servers:
- url: https://api.mospi.gov.in/
tags:
- name: AISHE.
  description: Indicator-wise aishe statistics in India.
paths:
  /api/aishe/getAisheRecords:
    get:
      summary: Get  data for an indicator
      description: |
        - **Required:** `indicator_code`  
        - **Filters (optional):** sub_indicator_code,gender_code,state_code,category_code,social_group_code,institution_type_code,faculty_type_code,learning_mode_code,year,
         

      parameters:
        - in: query
          name: indicator_code
          required: true
          schema: { type: integer }
          description: Indicator code (primary filter)
        - in: query
          name: limit
          schema: { type: integer, default: 20 }
        - in: query
          name: page
          schema: { type: integer, minimum: 1 }
        - in: query
          name: format
          schema:
            type: string
          description: Set to `xlsx` to download as excel

      responses:
        "200":
          description: A JSON array of user information
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
            text/csv:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
      security:
      - bearerAuth: []
 
components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      description: Bearer token to access these api endpoints
      name: Authorization
      in: header
x-original-swagger-version: "2.0"
