openapi: 3.0.1
info:
  title: API for Consumer Price Index(CPI)
  version: 1.0.11
servers:
- url: https://api.mospi.gov.in/
tags:
- name: Consumer Price Index and Inflation
  description: All-India and State-wise Consumer Price Index and Inflation.
- name: Item Indices and Inflation
  description: 'Item level Index and Inflation.'
paths:

  /api/cpi/getItemIndex:
    get:
      tags:
      - Item Indices and Inflation
      operationId: AiItemIndicesOrInflationCombined
      parameters:
      - name: base_year
        required: true
        in: query
        schema:
          default: "2012"
          enum:
          - "2012"
          - "2010"
      - name: year
        in: query
        description: Enter the Year (format YYYY.Comma separated for multiple values)
        schema:
          type: string
      - name: month_code
        in: query
        description: Enter the Month code (from 1-12.Comma separated for multiple values)
        schema:
          type: string
      - name: item_code
        in: query
        description: Enter the Item code
        schema:
          type: string
      - name: limit
        in: query
        description: Number of records per page (default 10)
        schema:
          type: integer
      - name: page
        in: query
        description: Enter the page no. (from 1 to n.)
        schema:
          type: string
      - name: Format
        required: true
        in: query
        description: Select the Output format
        schema:
          type: string
          default: JSON
          enum:
          - JSON
          - CSV
      responses:
        "200":
          description: A JSON array of user information
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
            text/csv:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
      
        "409":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Requested item wasn't found!
      security:
      - bearerAuth: []
  /api/cpi/getCPIIndex:
    get:
      tags:
      - Consumer Price Index and Inflation
      operationId: AiSiIndicesInflationRateCurrent
      parameters:
      - name: base_year
        required: true
        in: query
        schema:
          default: "2012"
          enum:
          - "2012"
          - "2010"
      - name: series
        required: true
        in: query
        schema:
          default: Current
          enum:
          - Current
          - Back
      - name: year
        in: query
        description:  Enter the Year (format YYYY.Comma separated for multiple values)
        schema:
          type: string
      - name: month_code
        in: query
        description: Enter the Month code (from 1-12.Comma separated for multiple values)
        schema:
          type: string
      - name: state_code
        in: query
        description:  Enter the State code (from 1-36 & 99 for all india comma separated for multiple values)
        schema:
          type: string
      - name: group_code
        in: query
        description: Enter the Group code(Comma separated for multiple values)
        schema:
          type: string
      - name: subgroup_code
        in: query
        description: Enter the Subgroup code(Comma separated for multiple values)
        schema:
          type: string
      - name: sector_code
        in: query
        description: Enter the Sector code (from 1-3.Comma separated for multiple values)
        schema:
          type: string
      - name: limit
        in: query
        description: Number of records per page (default 10)
        schema:
          type: integer
      - name: page
        in: query
        description: Enter the page no. (from 1 to n.)
        schema:
          type: string
      - name: Format
        required: true
        in: query
        description: Select the Output format
        schema:
          type: string
          default: JSON
          enum:
          - JSON
          - CSV
      responses:
        "200":
          description: A JSON array of user information

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
            text/csv:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
      
        "409":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Requested item wasn't found!
     
      security:
      - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      description: Bearer token to access these api endpoints
      name: Authorization
      in: header
x-original-swagger-version: "2.0"
