openapi: 3.0.1
info:
  title: Household Consumption Expenditure Survey

  version: 1.0.11
servers:
- url: https://api.mospi.gov.in/
tags:
- name: Household Consumption Expenditure Survey.
  description: Year-Wise Household Consumption Expenditure Survey.
paths:

  /api/hces/getHcesRecords:
    get:
      tags:
      - Household Consumption Expenditure Survey.
      operationId: HCESIndicatorValues.
      parameters:
      - name: indicator_code
        required: true
        in: query
        schema:
          default: "Average monthly per capita consumption expenditure (MPCE)"
          enum:
          - "Average monthly per capita consumption expenditure (MPCE)"
          - "Average monthly per capita consumption expenditure (MPCE) Over 12 Fractile Classes"
          - "Monthly Per Capita Consumption Expenditure (MPCE) over Broad Categories in 30 Days"
          - "Percentage Share of Monthly Per Capita Consumption Expenditure (MPCE) over Broad Categories in 30 Days"
          - "Average Per Capita Monthly Quantity Consumption "
          - "Average Monthly Per Capita Value of Consumption (Rs.)"
          - "Average Monthly Per Capita Consumption Expenditure (MPCE) across different Household Type"
          - "Average Monthly Per Capita Consumption Expenditure (MPCE) across different Social Group"
          - "Gini Coefficient for Per Capita Consumption Expenditure"

      - name: year
        in: query
        description: Enter the Year (format YYYY-YY/YYYY. Comma separated for multiple values)
        schema:
          type: string
      - name: sub_indicator_code
        in: query
        description: Enter the Sub Indicator code (from 1 to 3. Comma separated for multiple values)
        schema:
          type: string
      - name: state_code
        in: query
        description: Enter the State code (from 1 to 37. Comma separated for multiple values)
        schema:
          type: string
      - name: sector_code
        in: query
        description: Enter the Sector code (from 1 to 3. Comma separated for multiple values)
        schema:
          type: string
      - name: imputation_type_code
        in: query
        description: Enter the Imputation Type code (from 1 to 2. Comma separated for multiple values)
        schema:
          type: string
      - name: mpce_fractile_classes_code
        in: query
        description: Enter the MPCE Fractile Classes code (from 1 to 13. Comma separated for multiple values)
        schema:
          type: string
      - name: item_category_code
        in: query
        description: Enter the Item Category code (from 1 to 31. Comma separated for multiple values)
        schema:
          type: string
      - name: cereal_code
        in: query
        description: Enter the Cereal code (from 1 to 5. Comma separated for multiple values)
        schema:
          type: string
      - name: employment_of_households_code
        in: query
        description: Enter the Employment of Households code (from 1 to 11. Comma separated for multiple values)
        schema:
          type: string
      - name: social_group_code
        in: query
        description: Enter the Social Group code (from 1 to 5. Comma separated for multiple values)
        schema:
          type: string
      - name: page
        in: query
        description: Enter the page no. (from 1 to n.)
        schema:
          type: string

      - name: Format 
        required: true
        in: query
        description: Select the Output format
        schema:
          type: string
          default: JSON
          enum:
          - JSON
          - CSV
      responses:
        "200":
          description: A JSON array of user information
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
            text/csv:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid request body
      
        "409":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Requested item wasn't found!
      security:
      - bearerAuth: []
 
components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      description: Bearer token to access these api endpoints
      name: Authorization
      in: header
x-original-swagger-version: "2.0"
